# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/AnalyzerDialog.ui'
#
# Created: Mon Nov 25 20:58:23 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AnalyzerDialog(object):
    def setupUi(self, AnalyzerDialog):
        AnalyzerDialog.setObjectName("AnalyzerDialog")
        AnalyzerDialog.resize(421, 247)
        self.verticalLayout_2 = QtGui.QVBoxLayout(AnalyzerDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setObjectName("formLayout_2")
        self.analyzerTypeLabel = QtGui.QLabel(AnalyzerDialog)
        self.analyzerTypeLabel.setObjectName("analyzerTypeLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.analyzerTypeLabel)
        self.analyzerTypeComboBox = QtGui.QComboBox(AnalyzerDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyzerTypeComboBox.sizePolicy().hasHeightForWidth())
        self.analyzerTypeComboBox.setSizePolicy(sizePolicy)
        self.analyzerTypeComboBox.setObjectName("analyzerTypeComboBox")
        self.analyzerTypeComboBox.addItem("")
        self.analyzerTypeComboBox.addItem("")
        self.analyzerTypeComboBox.addItem("")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.analyzerTypeComboBox)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.line = QtGui.QFrame(AnalyzerDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.stackedWidget = QtGui.QStackedWidget(AnalyzerDialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.I2CPage = QtGui.QWidget()
        self.I2CPage.setObjectName("I2CPage")
        self.stackedWidget.addWidget(self.I2CPage)
        self.SPIPage = QtGui.QWidget()
        self.SPIPage.setObjectName("SPIPage")
        self.stackedWidget.addWidget(self.SPIPage)
        self.USARTPage = QtGui.QWidget()
        self.USARTPage.setObjectName("USARTPage")
        self.formLayout_5 = QtGui.QFormLayout(self.USARTPage)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_5.setObjectName("formLayout_5")
        self.baudLabel = QtGui.QLabel(self.USARTPage)
        self.baudLabel.setObjectName("baudLabel")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.baudLabel)
        self.baudComboBox = QtGui.QComboBox(self.USARTPage)
        self.baudComboBox.setEditable(True)
        self.baudComboBox.setObjectName("baudComboBox")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.baudComboBox)
        self.dataBitsLabel = QtGui.QLabel(self.USARTPage)
        self.dataBitsLabel.setObjectName("dataBitsLabel")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.dataBitsLabel)
        self.dataBitsComboBox = QtGui.QComboBox(self.USARTPage)
        self.dataBitsComboBox.setObjectName("dataBitsComboBox")
        self.dataBitsComboBox.addItem("")
        self.dataBitsComboBox.addItem("")
        self.dataBitsComboBox.addItem("")
        self.dataBitsComboBox.addItem("")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.dataBitsComboBox)
        self.stopBitsLabel = QtGui.QLabel(self.USARTPage)
        self.stopBitsLabel.setObjectName("stopBitsLabel")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.stopBitsLabel)
        self.stopBitsComboBox = QtGui.QComboBox(self.USARTPage)
        self.stopBitsComboBox.setObjectName("stopBitsComboBox")
        self.stopBitsComboBox.addItem("")
        self.stopBitsComboBox.addItem("")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.stopBitsComboBox)
        self.parityLabel = QtGui.QLabel(self.USARTPage)
        self.parityLabel.setObjectName("parityLabel")
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.parityLabel)
        self.parityComboBox = QtGui.QComboBox(self.USARTPage)
        self.parityComboBox.setObjectName("parityComboBox")
        self.parityComboBox.addItem("")
        self.parityComboBox.addItem("")
        self.parityComboBox.addItem("")
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.parityComboBox)
        self.stackedWidget.addWidget(self.USARTPage)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.buttonBox = QtGui.QDialogButtonBox(AnalyzerDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(AnalyzerDialog)
        self.stackedWidget.setCurrentIndex(2)
        self.baudComboBox.setCurrentIndex(5)
        self.dataBitsComboBox.setCurrentIndex(3)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), AnalyzerDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), AnalyzerDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AnalyzerDialog)

    def retranslateUi(self, AnalyzerDialog):
        AnalyzerDialog.setWindowTitle(QtGui.QApplication.translate("AnalyzerDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.analyzerTypeLabel.setText(QtGui.QApplication.translate("AnalyzerDialog", "Analyzer Type", None, QtGui.QApplication.UnicodeUTF8))
        self.analyzerTypeComboBox.setItemText(0, QtGui.QApplication.translate("AnalyzerDialog", "I2C", None, QtGui.QApplication.UnicodeUTF8))
        self.analyzerTypeComboBox.setItemText(1, QtGui.QApplication.translate("AnalyzerDialog", "SPI", None, QtGui.QApplication.UnicodeUTF8))
        self.analyzerTypeComboBox.setItemText(2, QtGui.QApplication.translate("AnalyzerDialog", "USART", None, QtGui.QApplication.UnicodeUTF8))
        self.baudLabel.setText(QtGui.QApplication.translate("AnalyzerDialog", "Baud", None, QtGui.QApplication.UnicodeUTF8))
        self.baudComboBox.setItemText(0, QtGui.QApplication.translate("AnalyzerDialog", "300", None, QtGui.QApplication.UnicodeUTF8))
        self.baudComboBox.setItemText(1, QtGui.QApplication.translate("AnalyzerDialog", "1200", None, QtGui.QApplication.UnicodeUTF8))
        self.baudComboBox.setItemText(2, QtGui.QApplication.translate("AnalyzerDialog", "2400", None, QtGui.QApplication.UnicodeUTF8))
        self.baudComboBox.setItemText(3, QtGui.QApplication.translate("AnalyzerDialog", "4800", None, QtGui.QApplication.UnicodeUTF8))
        self.baudComboBox.setItemText(4, QtGui.QApplication.translate("AnalyzerDialog", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.baudComboBox.setItemText(5, QtGui.QApplication.translate("AnalyzerDialog", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.baudComboBox.setItemText(6, QtGui.QApplication.translate("AnalyzerDialog", "38400", None, QtGui.QApplication.UnicodeUTF8))
        self.baudComboBox.setItemText(7, QtGui.QApplication.translate("AnalyzerDialog", "57600", None, QtGui.QApplication.UnicodeUTF8))
        self.baudComboBox.setItemText(8, QtGui.QApplication.translate("AnalyzerDialog", "115200", None, QtGui.QApplication.UnicodeUTF8))
        self.dataBitsLabel.setText(QtGui.QApplication.translate("AnalyzerDialog", "Data Bits", None, QtGui.QApplication.UnicodeUTF8))
        self.dataBitsComboBox.setItemText(0, QtGui.QApplication.translate("AnalyzerDialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.dataBitsComboBox.setItemText(1, QtGui.QApplication.translate("AnalyzerDialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.dataBitsComboBox.setItemText(2, QtGui.QApplication.translate("AnalyzerDialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.dataBitsComboBox.setItemText(3, QtGui.QApplication.translate("AnalyzerDialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.stopBitsLabel.setText(QtGui.QApplication.translate("AnalyzerDialog", "Stop Bits", None, QtGui.QApplication.UnicodeUTF8))
        self.stopBitsComboBox.setItemText(0, QtGui.QApplication.translate("AnalyzerDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.stopBitsComboBox.setItemText(1, QtGui.QApplication.translate("AnalyzerDialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.parityLabel.setText(QtGui.QApplication.translate("AnalyzerDialog", "Parity", None, QtGui.QApplication.UnicodeUTF8))
        self.parityComboBox.setItemText(0, QtGui.QApplication.translate("AnalyzerDialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.parityComboBox.setItemText(1, QtGui.QApplication.translate("AnalyzerDialog", "Even", None, QtGui.QApplication.UnicodeUTF8))
        self.parityComboBox.setItemText(2, QtGui.QApplication.translate("AnalyzerDialog", "Odd", None, QtGui.QApplication.UnicodeUTF8))

