# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/MainWindow.ui'
#
# Created: Sun Nov  3 21:06:00 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(911, 657)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topRowLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.topRowLayoutWidget.setObjectName("topRowLayoutWidget")
        self.topRowLayout = QtGui.QHBoxLayout(self.topRowLayoutWidget)
        self.topRowLayout.setContentsMargins(12, 12, -1, -1)
        self.topRowLayout.setObjectName("topRowLayout")
        self.label = QtGui.QLabel(self.topRowLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.topRowLayout.addWidget(self.label)
        self.protocolComboBox = QtGui.QComboBox(self.topRowLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.protocolComboBox.sizePolicy().hasHeightForWidth())
        self.protocolComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.protocolComboBox.setFont(font)
        self.protocolComboBox.setObjectName("protocolComboBox")
        self.protocolComboBox.addItem("")
        self.protocolComboBox.addItem("")
        self.protocolComboBox.addItem("")
        self.protocolComboBox.addItem("")
        self.topRowLayout.addWidget(self.protocolComboBox)
        self.label_2 = QtGui.QLabel(self.topRowLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.topRowLayout.addWidget(self.label_2)
        self.sampleRateComboBox = QtGui.QComboBox(self.topRowLayoutWidget)
        font = QtGui.QFont()
        self.sampleRateComboBox.setFont(font)
        self.sampleRateComboBox.setObjectName("sampleRateComboBox")
        self.sampleRateComboBox.addItem("")
        self.topRowLayout.addWidget(self.sampleRateComboBox)
        self.label_3 = QtGui.QLabel(self.topRowLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.topRowLayout.addWidget(self.label_3)
        self.triggerChannelComboBox = QtGui.QComboBox(self.topRowLayoutWidget)
        self.triggerChannelComboBox.setObjectName("triggerChannelComboBox")
        self.triggerChannelComboBox.addItem("")
        self.triggerChannelComboBox.addItem("")
        self.triggerChannelComboBox.addItem("")
        self.triggerChannelComboBox.addItem("")
        self.topRowLayout.addWidget(self.triggerChannelComboBox)
        self.triggerSlopeComboBox = QtGui.QComboBox(self.topRowLayoutWidget)
        self.triggerSlopeComboBox.setObjectName("triggerSlopeComboBox")
        self.triggerSlopeComboBox.addItem("")
        self.triggerSlopeComboBox.addItem("")
        self.topRowLayout.addWidget(self.triggerSlopeComboBox)
        self.startButton = QtGui.QPushButton(self.topRowLayoutWidget)
        self.startButton.setObjectName("startButton")
        self.topRowLayout.addWidget(self.startButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.topRowLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.topRowLayoutWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.analyzerWidget = AnalyzerWidget(self.centralwidget)
        self.analyzerWidget.setProperty("cursor", QtCore.Qt.CrossCursor)
        self.analyzerWidget.setMouseTracking(True)
        self.analyzerWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.analyzerWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.analyzerWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.analyzerWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.analyzerWidget.setBackgroundBrush(brush)
        self.analyzerWidget.setInteractive(False)
        self.analyzerWidget.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.analyzerWidget.setRenderHints(QtGui.QPainter.TextAntialiasing)
        self.analyzerWidget.setTransformationAnchor(QtGui.QGraphicsView.AnchorUnderMouse)
        self.analyzerWidget.setObjectName("analyzerWidget")
        self.horizontalLayout.addWidget(self.analyzerWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 911, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSave_to_Spreadsheet = QtGui.QAction(MainWindow)
        self.actionSave_to_Spreadsheet.setObjectName("actionSave_to_Spreadsheet")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_to_Spreadsheet)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Logician Logic Analyzer", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Protocol:", None, QtGui.QApplication.UnicodeUTF8))
        self.protocolComboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "Select a suitable communication protocol.", None, QtGui.QApplication.UnicodeUTF8))
        self.protocolComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "General I/O", None, QtGui.QApplication.UnicodeUTF8))
        self.protocolComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "I2C", None, QtGui.QApplication.UnicodeUTF8))
        self.protocolComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "SPI", None, QtGui.QApplication.UnicodeUTF8))
        self.protocolComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "USART", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Sample Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleRateComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "1 MS/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Trigger:", None, QtGui.QApplication.UnicodeUTF8))
        self.triggerChannelComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Channel 1", None, QtGui.QApplication.UnicodeUTF8))
        self.triggerChannelComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Channel 2", None, QtGui.QApplication.UnicodeUTF8))
        self.triggerChannelComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Channel 3", None, QtGui.QApplication.UnicodeUTF8))
        self.triggerChannelComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Channel 4", None, QtGui.QApplication.UnicodeUTF8))
        self.triggerSlopeComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Rising", None, QtGui.QApplication.UnicodeUTF8))
        self.triggerSlopeComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Falling", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_to_Spreadsheet.setText(QtGui.QApplication.translate("MainWindow", "Save to Spreadsheet...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))

from ui.widgets import AnalyzerWidget
